### ISSUE TITLE
improve country codes by adding 3 letter country code ?

### ISSUE THREAD

**Issue by jas1** [CaRdiffR/tdor#11]
Hi , I worked with the data on #tidytuesday last TDOR , 

Think you can really improve the dataset by adding a 3 letter code for countries (iso_a3) country codes. 

you can check my contribution on: 
https://github.com/jas1/tidytuesday/tree/master/jas1_weeks/2018-11-20

if you prefer a PR , just tell me ill fork and add the suggestion,  but preferred just to check with you before doing the thing.

any comments you can reach me here or twitter.

**Comment by annajayne** [comment]
That's a good idea.

I've been generating the CSV files from spreadsheets, so it strikes me that adding country codes there would be a little messy and potentially time consuming.

However, it would be very easy to add them to both the exported data from the website and (when we implement it) the JSON web service interface which I'm thinking about adding.

The latter could act as a realtime data source for an R package in place of the existing CSV files, so that would directly solve the problem.

Using a web service interface you would also get access to other fields not currently included in the CSV files, such as timestamps for the most recent updates, the report UID etc.

**Comment by annajayne** [comment]
Thanks :)

I'm probably going to have a bit of a look at the design for a JSON web service API over Christmas, so it shouldn't actually be that long before something which represents the live data is available.

The website already knows the country codes (it parses the country name when the CSV files are uploaded), so the info we need is actually already available internally.

For the most part until then I'd prefer to focus more on processing the backlog of raw news reports we have already made a note of for later analysis (those are starting to really pile up!) rather than devote time to amend the CSV format. Similar considerations apply to breaking up the "Location" field to street/city/state or equivalent etc.

It's worth being aware that there are so many reports for which we have very little information, if any - and around 300 historic reports (going back to 1972!) which haven't been entered yet. With some reports taking a considerable time to research and write up it all competes for time.

Incidentally the Excel files I referred to in the reply above to are actually the annotated multi-sheet (1 per year, each with a summary sheet and 1 sheet per month) ones I use to generate the CSV files themselves uploaded to the website.

As such writing new spreadsheets probably won't help as much as parsing each of the existing ones, amending each sheet with new data and saving them with all formatting intact would. But I suspect that would probably be more hassle than it's worth.

**Comment by jas1** [comment]
understood pririties =) . feel free to close ;)

**Comment by hturner** [comment]
Thanks for the suggestion @jas1, we can do this for the tdor R package (@annajayne is working on the original source data). I will add a clean issue for our hackathon tomorrow as this thread contains various old links and information which might be confusing!
